title: My Academic Portfolio
author: Bilgehan Emiral
description: A portfolio showcasing my academic work, projects, and professional interests.
baseurl: /b-emiral
url: https://b-emiral.github.io
theme: jekyll-theme-minimal
