title: "My Academic Portfolio"
author: "Bilgehan Emiral"
description: "A portfolio showcasing my academic work, projects, and professional interests."
baseurl: ""
url: "https://yourgithubusername.github.io"
theme: minima
