title: Bilgehan Emiral
author: Bilgehan Emiral
description: A portfolio showcasing my academic work, projects, and professional interests.
baseurl:
url: https://b-emiral.github.io
theme: jekyll-theme-minimal
